# 公共参数
num_trees: 4
max_depth: 3
complete_secure: 0
hist_sub: true
max_bin: 32

# guest方（B方、带标签方）独有的
learning_rate: 0.2
objective: 'binary:bce'
num_class: 2
l2: 0.1
l1: 0
min_impurity_split: 0.01
min_sample_split: 2
min_leaf_node: 1
min_child_weight: 1
goss: False
goss_start_iter: 0
top_rate: 0.2
other_rate: 0.1
gh_pack: true
split_info_pack: true
random_seed: 42


# 其它参数
log_level: 'ERROR'