num_trees: 1000
max_depth: 5
complete_secure: 0
hist_sub: true
max_bin: 32
learning_rate: 0.1
objective: multi:ce
num_class: 4
l2: 0.1
l1: 0
min_impurity_split: 0.01
min_sample_split: 2
min_leaf_node: 1
min_child_weight: 1
goss: false
goss_start_iter: 0
top_rate: 0.2
other_rate: 0.1
gh_pack: true
split_info_pack: true
random_seed: 42
log_level: ERROR
