num_trees: 3
max_depth: 3
complete_secure: 0
learning_rate: 0.3
objective: "binary:bce"
num_class: 1
max_bin: 32
l2: 0.1
l1: 0
min_impurity_split: 1e-2
min_sample_split: 2
min_leaf_node: 1
min_child_weight: 1
goss: false
goss_start_iter: 0
top_rate: 0.2
other_rate: 0.1
gh_pack: true
split_info_pack: true
hist_sub: true
random_seed: 42
log_level: ERROR